"""Restore migration baseline

Revision ID: fb85aaf61a44
Revises: 
Create Date: 2026-09-21 09:45:48.416215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb85aaf61a44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'expected_output',
                sa.Text(),
                nullable=False,
                server_default=''
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('expected_output')

    # ### end Alembic commands ###
